### ISSUE TITLE
The `lastLine` variable is undefined, when a new record  is appended into `new SSHConfig`.

### ISSUE THREAD

**Issue by hipoyang** [cyjake/ssh-config#16]
https://github.com/cyjake/ssh-config/blob/148c0a5a1352656fe3a4288367daa27eaf133ac5/index.js#L107

I make a new SSHConfig instance,  and would like to append new record to it. But it's not working, since `lastLine.config` goes runtime error.

**Comment by cyjake** [comment]
fixed with v1.1.6
