### ISSUE TITLE
Quoted hosts with spaces are not parsed correctly

### ISSUE THREAD

**Issue by roblourens** [cyjake/ssh-config#17]
Host values can be quoted to include spaces. For example:

```
Host abc "foo bar"
    ...
```

defines two hosts, "abc" and "foo bar". Maybe I can provide a PR.

**Comment by cyjake** [comment]
@roblourens I wasn't aware that space separated hosts were possible. The manpage only describes `Host` with single hostname or [pattern](https://www.freebsd.org/cgi/man.cgi?query=ssh_config&sektion=5#PATTERNS). Can you provide more details on this a bit?

**Comment by roblourens** [comment]
From the first section,

> The file contains keyword-argument	pairs, one per line.  Lines starting
     with `#' and empty	lines are interpreted as comments.  Arguments may
     optionally	be enclosed in double quotes (") in order to represent argu-
     ments containing spaces.

**Comment by cyjake** [comment]
Ah I see. Guess I jumped to the conclusion that hostnames can't have spaces too quickly.

**Comment by cyjake** [comment]
```js
 Host    Restricts the following declarations (up to the next Host key‐
         word) to be only for those hosts that match one of the patterns
         given after the keyword.  If more than one pattern is provided,
         they should be separated by whitespace.
```

Here's the changes I'm going to make:

- Make `Host` with multiple values separated by spaces possible
- Parse double quoted strings correctly (currently the value part is parsed as is)

**Comment by cyjake** [comment]
v2.0.0-alpha.1 published. @roblourens Please give this version a try :-/

**Comment by cyjake** [comment]
oh, documentations is a bit behind. Here's the breaking change of v2:

```js
// v1 compatible
parse('Host foo') // => { param: 'Host', value: 'foo' }
parse('Host "foo bar"') // => { param: 'Host', value: 'foo bar' }

// v2 breaking change
parse('Host "foo bar" *.baz') // => { param: 'Host', value: ['foo bar', '*.bar'] }

I'll update the documentation part asap
