### ISSUE TITLE
Untrimmed host names are returned

### ISSUE THREAD

**Issue by roblourens** [cyjake/ssh-config#18]
The change to parsing Hosts works great, except that extra whitespace is not trimmed. I can easily work around that but you might want to clean it up. Example:

```
Host me local    wi*ldcard?  thisVM "two words"
```

is parsed to include an empty Host and leading whitespace.

![image](https://user-images.githubusercontent.com/323878/59312644-b7cf2380-8c62-11e9-8480-4fc015cba329.png)

**Comment by cyjake** [comment]
nice catch! 👍 
fixed in v2.0.0-alpha.2
