### ISSUE TITLE
"Host *+*" pattern breaks ssh-config

### ISSUE THREAD

**Issue by roblourens** [cyjake/ssh-config#19]
From https://github.com/microsoft/vscode-remote-release/issues/612

This is weird but if I have an entry in the ssh config that starts with

`Host *+*`

Then `compute` will throw an exception.

This is apparently valid, it's referenced here: https://en.wikibooks.org/wiki/OpenSSH/Cookbook/Proxies_and_Jump_Hosts

For your glob to regex conversion, maybe escape special regex characters that are not handled as part of a glob pattern.

**Comment by cyjake** [comment]
nice catch 👍

**Comment by cyjake** [comment]
v2.0.0-alpha.3 released

**Comment by roblourens** [comment]
Thanks!
