### ISSUE TITLE
Tab character in config causes issues

### ISSUE THREAD

**Issue by roblourens** [cyjake/ssh-config#20]
From https://github.com/microsoft/vscode-remote-release/issues/909

Have an ssh config like

```
Host tab
    HostName	localhost

Host missing
    HostName localhost
```

Note the tab character between param/value under the 'tab' host. ssh-config parses the whole line as one param, and the next host is parsed as the value.

![image](https://user-images.githubusercontent.com/323878/60749256-1af36380-9f4c-11e9-9d92-e4fe616c41c5.png)

**Comment by cyjake** [comment]
Interesting, I thought param/value can only be separated with space or `=`.

**Comment by cyjake** [comment]
The manpage says they should be separated with space or `=`, the software recognizes `\t` as well. I should be practical and fix this :-/

**Comment by cyjake** [comment]
v2.0.0-beta.1 released
