### ISSUE TITLE
Allow consumers to pass in parsed nodes to `append()`

### ISSUE THREAD

**Issue by connor4312** [cyjake/ssh-config#22]
Thanks for your work on this library, it's super useful!

We ran into some awkward behavior using the [`append()`](https://github.com/cyjake/ssh-config/blob/320854e59f30968bab81d1c938380dba10dd28fd/index.js#L96) API. Right now, it takes a map of properties, and depends on property order to nest items under the `Host` directive. We encountered some initial difficulty with this, as the importance of property ordering wasn't obvious to us, and we end up having to re-build our objects to ensure the key order to fix this.

It'd be convenient if `append()` was able to take the same "syntax tree" node type that we get back from `parse()`. This allows our logic to deal with a unified data type, and would also removes ambiguity in the order. (At the cost of having a slightly more verbose process to create the directive to append.)

I think this could be implemented in a backwards-compatible way doing something like this:

```js
  /**
   * Append new section to existing ssh config.
   */
  append(...opts) {
 
  const sections = opts
    .map(opt => 'param' in opt
      ? convertAstToString(opt) // new AST => string
      : convertDictionaryToString(opt)) // existing map => string
    .join('\n');
 
  // append section fragment to file
```

Thoughts? I'm happy to take a shot at getting a PR in for this if you're interested.

**Comment by cyjake** [comment]
@connor4312 Glad it helps!

The parsed AST, an instance of SSHConfig, is a subclass of Array, which means you can `.push()` or `.concat()` new sections in AST directly. For example:

```js
const config = new SSHConfig()
config.push(SSHConfig.parse(`
Host ness
  HostName lochness.com
  User dinosaur
`))
```

Changing `.append()` in a backward compatible way sure is possible, one single check shall suffice:

```js
```

**Comment by cyjake** [comment]
@connor4312 Can you provide more detail (such as the actual `.append()` call you were trying)? I need to confirm whether I'd understood your question in the first place.

**Comment by connor4312** [comment]
I think `push` solves the need. I failed to notice that SSHConfig subclassed arrays. Thanks for the followup! 🙂
