### ISSUE TITLE
append with extra newline?

### ISSUE THREAD

**Issue by roblourens** [cyjake/ssh-config#23]
I would like to be able to add a new config, and have it formatted with an extra newline between the previous entry and the new entry. It's not clear, is there any way to do that currently?

Like

```
Host foo
  HostName existing

Host bar
  HostName newconfig
```

**Comment by cyjake** [comment]
Currently it's determined by the last line of previous section. For brevity, I think it's safe to add one extra line breaking when appending with config objects. I'll give it a try today.

**Comment by cyjake** [comment]
@roblourens I've changed `.append()` behavior to always insert a line break before appending (previously it is inserted only if the original last line has no line break)

v2.0.0 is now released.

**Comment by roblourens** [comment]
Thanks!

**Comment by roblourens** [comment]
I think what I actually wanted is `\n\n` for an empty line between the new and old configs

**Comment by cyjake** [comment]
I prefer separating sections with two linebreaks as well. Changing `.append()` might need a major version though. I'll see what I can do.

**Comment by cyjake** [comment]
btw, is it possible of you to make sure previous sections is ended with line break?

**Comment by roblourens** [comment]
It doesn't look like it's possible, at least not with the exposed api..
