### ISSUE TITLE
Can't parse multiple LocalForward directives

### ISSUE THREAD

**Issue by roblourens** [cyjake/ssh-config#30]
It's valid to have multiple forwarding directives, like

```
Host my-host
	HostName 123.123.123.123
	LocalForward 5921 localhost:5901
	LocalForward 9877 localhost:7899
```

but ssh-config only returns the first one.

**Comment by cyjake** [comment]
v4.0.0 released (bumped major version because of breaking change on `.compute()` api)

**Comment by roblourens** [comment]
Thanks!
