### ISSUE TITLE
Empty string host returned for trailing whitepace

### ISSUE THREAD

**Issue by roblourens** [cyjake/ssh-config#32]
This might be new?

Have a config with trailing whitespace on the Host line like

```
Host penlv  
  HostName penlv-devbox
  User penlv
```

I get an array for "value" which includes an empty string like this:

![image](https://user-images.githubusercontent.com/323878/73569060-850ab300-441e-11ea-9324-f53ba4439a2c.png)

**Comment by cyjake** [comment]
It's an overlooked old issue. I'll fix right away

**Comment by cyjake** [comment]
v4.0.1 released @roblourens
