### ISSUE TITLE
Parse Include statement at end of file

### ISSUE THREAD

**Issue by roblourens** [cyjake/ssh-config#42]
`Include otherfile` is handled correctly at the beginning of the file, but when it appears after another config, it gets added to that config. Example

```
Host someHost
    HostName 123.123.123.123

Include config3
```

Parses like this
![image](https://user-images.githubusercontent.com/323878/109730265-15f61580-7b6e-11eb-8baa-dc1918c3a10e.png)

**Comment by cyjake** [comment]
It's intended behavior. According to ssh_config(5), `Include` might appear inside `Match` or `Host` to perform conditional config inclusion. 

> Include the specified configuration file(s).  Multiple pathnames
> may be specified and each pathname may contain glob(7) wildcards
> and, for user configurations, shell-like `~' references to user
> home directories. Files without absolute paths are assumed to be
> in ~/.ssh if included in a user configuration file or /etc/ssh if
> included from the system configuration file.  Include directive
> may appear inside a Match or Host block to perform conditional
> inclusion.

**Comment by roblourens** [comment]
Oh, you're right. Confirmed that ssh handles it this way. I think I used to know that.
