### ISSUE TITLE
Typescript Declaration ? 

### ISSUE THREAD

**Issue by monil-patel** [cyjake/ssh-config#49]
I was struggling to get type declarations to work after importing ssh-config 
![image](https://user-images.githubusercontent.com/45443099/150203706-bdc40618-3416-4764-ad24-ef5c157299aa.png)

It looks like typings were adding here #47 , So based on this doc I would assume types should be automatically picked up? 
https://www.typescriptlang.org/docs/handbook/declaration-files/consumption.html#consuming
![image](https://user-images.githubusercontent.com/45443099/150203916-3bb299eb-c35f-4a20-8dd6-0494e7e92d46.png)

Is it possible the "types" property needs to be set in the package.json. (This is new learning for me so apologies if not the right)
https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#including-declarations-in-your-npm-package

**Comment by cyjake** [comment]
Yikes, guess I forgot to add the `types` property. I'll release a fix today, thanks for noticing!

**Comment by cyjake** [comment]
v4.1.2 released

**Comment by monil-patel** [comment]
@cyjake appreciate the quick fix!
