### ISSUE TITLE
IdentityAgent are not quoted where there are spaces

### ISSUE THREAD

**Issue by Troublor** [cyjake/ssh-config#51]
#37 aimed to add quotes to most of the fields, but `IdentityAgent` is not one of them. 
It would be better to support IdentityAgent as well. 
`IdentityAgent` usually has spaces in the value when we use thrid-party ssh agents on MacOS, where many system directory path contains space, e.g., `~/Library/Group Containers` for `1password ssh agent`.

**Comment by cyjake** [comment]
@Troublor Thanks for reporting! fixed and released with v4.1.3
