### ISSUE TITLE
`.push` appends `undefined`

### ISSUE THREAD

**Issue by ecumene** [cyjake/ssh-config#53]
When using `.push`, I encountered some unexpected behaviour

```
config.push(SSHConfig.parse(`
Host ness
  HostName lochness.com
  User dinosaur
`))
```
When I stringify the config after doing this, I get undefined (in a string...)
```
SSHConfig.stringify(config); // "undefined"
```

However, when using `.append()` it works as expected.

**Comment by cyjake** [comment]
`SSHConfig.parse(string)` returns an instance of SSHConfig, which is a subclass of Array. Hence the example in the issue needs to be:

```js
config.push(...SSHConfig.parse(`
Host ness
  HostName lochness.com
  User dinosaur
`))
```

or with `.append(object)`

```js
config.append({
  Host: 'ness',
  HostName: 'lockness.com',
  User: 'dinosaur',
})
```

I wonder if `.append(SSHConfig)` really works though, it doesn't look so by examine the implementation

**Comment by ecumene** [comment]
I tried spreading SSHConfig and it worked! I was working off of this doc. Should it be updated?

https://github.com/cyjake/ssh-config/blob/cd690893c80b4cd3c0393130bf5f2b7edc03cc02/Readme.md?plain=1#L124
