### ISSUE TITLE
[question] How to add START and END block comments?

### ISSUE THREAD

**Issue by BrunoQuaresma** [cyjake/ssh-config#61]
Hi, I would like to add block comments around the config like this:

```
--- START CODER VSCODE ---
Host coder-vscode--*
	ProxyCommand "...." %h
	ConnectTimeout 0
	StrictHostKeyChecking no
	UserKnownHostsFile /dev/null
	LogLevel ERROR
 --- END CODER VSCODE ---
```

But I'm not finding a good way to do that. Thanks in advance!

**Comment by cyjake** [comment]
lines starting with `#` will be interpreted as comments, you can manually push, unshift, or splice comment into the AST

```js
config.unshift({
    type: 2,
    content: '# start coder vscode',
    before: '\n',
    after: '\n'
});

config.push({
    type: 2,
    content: '# end coder vscode',
    before: '\n',
    after: '\n'
});
```

**Comment by BenjaminGrayNp1** [comment]
Looks like there's nothing left to do here; SSH config doesn't support block comments, so the parser won't help with that.

**Comment by cyjake** [comment]
yep, I'll close this one
