### ISSUE TITLE
Can't parse config that includes comment after match statement

### ISSUE THREAD

**Issue by roblourens** [cyjake/ssh-config#73]
Reported in https://github.com/microsoft/vscode-remote-release/issues/9479

Add this to the top of an ssh config

```
# CLOUDFLARE SETUP https://URL_REDACTED
Match all # CLOUDFLARE SETUP
    Include /Users/mtovino/.ssh/cloudflare/config # CLOUDFLARE SETUP
```

The Remote-SSH extension calls `parse` on the config. The error `Missing value for match criteria SETUP` is thrown with this stack

```
directive (/Users/roblou/code/vscode-remote-ssh/open-ssh-remote/node_modules/ssh-config/src/ssh-config.js:453)
line (/Users/roblou/code/vscode-remote-ssh/open-ssh-remote/node_modules/ssh-config/src/ssh-config.js:466)
parse (/Users/roblou/code/vscode-remote-ssh/open-ssh-remote/node_modules/ssh-config/src/ssh-config.js:473)
getSshConfiguration (/Users/roblou/code/vscode-remote-ssh/open-ssh-remote/src/ssh-hosts.ts:136)
```

**Comment by roblourens** [comment]
Could be from https://github.com/cyjake/ssh-config/commit/da978de1b728ed7880cdedd4570be2b5f3068b0a? I got this after upgrading from `4.1.1`

**Comment by cyjake** [comment]
is that valid ssh-config file? I thought comments can only be lines starting with `#`

> Lines starting with ‘#’ and empty lines are interpreted as comments.

**Comment by cyjake** [comment]
I can tweak the parser to yield correct match criteria but the trailing comments won't be persisted if stringified back, is that acceptable?

**Comment by cyjake** [comment]
looks like the trailing comments can be handled as well, here's the pr. I'll release a version later if everything is green.

**Comment by roblourens** [comment]
Good point, I remember seeing that note now, but I think many people write trailing comments since ssh seems to handle them anyway.
