### ISSUE TITLE
'compute' can throw for user using ldap

### ISSUE THREAD

**Issue by roblourens** [cyjake/ssh-config#77]
Original issue https://github.com/microsoft/vscode-remote-release/issues/9649#issuecomment-2015267838

Here, https://github.com/cyjake/ssh-config/blob/162eaa36ad7a0ffce0a463322e50a1633f9bd478/src/ssh-config.ts#L172C15-L172C26

`os.userInfo` can throw for some users https://nodejs.org/api/os.html#osuserinfooptions

But it looks like `User` is optional here, or may not be needed, what do you think?

**Comment by cyjake** [comment]
can `process.env.USER` be used as a fallback? otherwise I'd have to add a asynchronous `whoami` call, which might impose more change

**Comment by roblourens** [comment]
Probably, but I'm not sure of the significance of having the username here.

**Comment by cyjake** [comment]
whoa, the commit references looks overwhelming, sorry about that, was fighting with code coverage (yet still failed). The username is needed to calculate Match directives (might be referenced in the criteria). 

i'll release a patch version tonight.
