### ISSUE TITLE
= in ProxyCommand are lost

### ISSUE THREAD

**Issue by roblourens** [cyjake/ssh-config#84]
- Have a config that contains
```
Host YYYY
  HostName YYYY
  IdentityFile ~/.ssh/id_rsa
  StrictHostKeyChecking no
  UserKnownHostsFile /dev/null
  ProxyCommand ssh -i ~/.ssh/id_rsa -W %h:%p -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null XXX@ZZZ
  User XXX
```
- I parse the config, `.prepend` to add an entry, and `toString()` the config

The config now looks like

```
Host YYYY
  HostName YYYY
  IdentityFile ~/.ssh/id_rsa
  StrictHostKeyChecking no
  UserKnownHostsFile /dev/null
  ProxyCommand ssh -i ~/.ssh/id_rsa -W %h:%p -o StrictHostKeyChecking no -o UserKnownHostsFile /dev/null XXX@ZZZ
  User XXX
```

the `=` have been removed from ProxyCommand. If I start with the command in double quotes, it doesn't remove the `=` but it does remove the quotes.

**Comment by cyjake** [comment]
it looks like the directive value ast needs to be changed to fix this issue, I'll release a major version later

**Comment by QiuMP** [comment]
Any update about this issue?

**Comment by cyjake** [comment]
v5.0.0 released
